In [1]:
from Bimatrix import PayoffMatrix, Bimatrix, processArguments
import torch
import fractions

In [2]:
payoff = PayoffMatrix(None,10,5)

In [3]:
payoff.__str__()


tensor([[37.2275,  0.4307, 32.7115, 19.3120, 57.2170],
        [88.3238, 40.2288, 62.9738, 88.7352, 45.2705],
        [74.2997, 54.6790,  0.1541, 33.3198, 20.2593],
        [ 0.2538, 77.5777, 48.2908, 57.4598, 50.5202],
        [52.6620, 30.1810, 53.2693, 68.9827, 32.2855],
        [34.9280, 76.9346, 38.8301, 50.6637,  4.8628],
        [48.2200,  8.2309, 40.1322, 68.0226, 34.7707],
        [24.5498,  3.8404, 65.4737, 65.4588, 42.8959],
        [40.2370, 52.3630, 62.4971,  5.1400, 79.5775],
        [43.9009, 65.5976,  0.3441, 35.9327,  8.7863]], dtype=torch.float64)

In [4]:
payoff = PayoffMatrix(None, 2, 2)

In [5]:
torch.concat((payoff.negmatrix, torch.Tensor([[0,0]])))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [6]:
game = Bimatrix(None, 5,5)

In [7]:
print(game)

# m,n= 
5 5
# A= 
 tensor([[19.6506, 57.1207, 12.3970, 13.0856, 75.0671],
        [12.2465, 49.1033, 38.7688, 93.5781, 17.6382],
        [55.3086, 20.4362,  5.3255, 90.7580, 39.0415],
        [97.3700, 71.9183, 79.4871, 10.7944, 11.0530],
        [48.3489,  3.2753, 72.0476, 40.8152, 25.8745]], dtype=torch.float64)
# B= tensor([[10.7578, 49.2832, 95.4756, 29.2930,  6.9899],
        [ 9.3459,  1.3043,  7.8746, 38.6530, 34.5150],
        [91.1131, 90.9082, 70.4932, 52.0813, 36.1970],
        [65.8465, 23.1314, 23.3531, 20.1406, 33.1066],
        [71.5607, 34.9038,  2.6634, 57.8797, 92.0479]], dtype=torch.float64)


In [8]:
print(game)

# m,n= 
5 5
# A= 
 tensor([[19.6506, 57.1207, 12.3970, 13.0856, 75.0671],
        [12.2465, 49.1033, 38.7688, 93.5781, 17.6382],
        [55.3086, 20.4362,  5.3255, 90.7580, 39.0415],
        [97.3700, 71.9183, 79.4871, 10.7944, 11.0530],
        [48.3489,  3.2753, 72.0476, 40.8152, 25.8745]], dtype=torch.float64)
# B= tensor([[10.7578, 49.2832, 95.4756, 29.2930,  6.9899],
        [ 9.3459,  1.3043,  7.8746, 38.6530, 34.5150],
        [91.1131, 90.9082, 70.4932, 52.0813, 36.1970],
        [65.8465, 23.1314, 23.3531, 20.1406, 33.1066],
        [71.5607, 34.9038,  2.6634, 57.8797, 92.0479]], dtype=torch.float64)


In [9]:
print(game.LemkeHowson  ("1"))

n= 12
M=                                                                                                                                   
tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(-1.)  tensor(0.)
tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(-1.)  tensor(0.)
tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(-1.)  tensor(0.)
tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(-1.)  tensor(0.)
tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(-1.)  tensor(0.)
tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.)  tensor(0.) tensor(-1.)
tensor(0.) tensor(0.) tensor(0.) tensor(0.) tensor(0.) t

In [10]:
fractions.Fraction("1.2")

Fraction(6, 5)