In [1]:
from Bimatrix import PayoffMatrix, Bimatrix
import torch
import fractions

In [2]:
payoff = PayoffMatrix(None,10,5)

In [3]:
payoff.__str__()


tensor([[0.3567, 0.6481, 0.5692, 0.8437, 0.0193],
        [0.8287, 0.8941, 0.7258, 0.1050, 0.8544],
        [0.6574, 0.6411, 0.8094, 0.0917, 0.5125],
        [0.3945, 0.2629, 0.2246, 0.8111, 0.4025],
        [0.5137, 0.7813, 0.6260, 0.5172, 0.5497],
        [0.5893, 0.4843, 0.2257, 0.6175, 0.9537],
        [0.0815, 0.4810, 0.9550, 0.6347, 0.6619],
        [0.7282, 0.4148, 0.6941, 0.7367, 0.2527],
        [0.9516, 0.7117, 0.4548, 0.0059, 0.8623],
        [0.7282, 0.5018, 0.0614, 0.3676, 0.4441]], dtype=torch.float64)

In [4]:
payoff = PayoffMatrix(None, 2, 2)

In [5]:
torch.concat((payoff.negmatrix, torch.Tensor([[0,0]])))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [6]:
game = Bimatrix(None, 5,5)

In [7]:
print(game)

# m,n= 
5 5
# A= 
 tensor([[0.1126, 0.5581, 0.2404, 0.7318, 0.2083],
        [0.0310, 0.1893, 0.4316, 0.4773, 0.1555],
        [0.5492, 0.9047, 0.5648, 0.1582, 0.0883],
        [0.5777, 0.2975, 0.4932, 0.0145, 0.7713],
        [0.0762, 0.3738, 0.7390, 0.6566, 0.1528]], dtype=torch.float64)
# B= tensor([[0.0961, 0.2167, 0.4386, 0.1467, 0.0959],
        [0.4909, 0.6475, 0.2674, 0.0245, 0.1421],
        [0.6234, 0.2625, 0.9979, 0.1306, 0.0469],
        [0.1011, 0.7563, 0.1581, 0.1801, 0.0925],
        [0.2929, 0.8376, 0.0704, 0.6827, 0.3444]], dtype=torch.float64)


In [8]:
print(game)

# m,n= 
5 5
# A= 
 tensor([[0.1126, 0.5581, 0.2404, 0.7318, 0.2083],
        [0.0310, 0.1893, 0.4316, 0.4773, 0.1555],
        [0.5492, 0.9047, 0.5648, 0.1582, 0.0883],
        [0.5777, 0.2975, 0.4932, 0.0145, 0.7713],
        [0.0762, 0.3738, 0.7390, 0.6566, 0.1528]], dtype=torch.float64)
# B= tensor([[0.0961, 0.2167, 0.4386, 0.1467, 0.0959],
        [0.4909, 0.6475, 0.2674, 0.0245, 0.1421],
        [0.6234, 0.2625, 0.9979, 0.1306, 0.0469],
        [0.1011, 0.7563, 0.1581, 0.1801, 0.0925],
        [0.2929, 0.8376, 0.0704, 0.6827, 0.3444]], dtype=torch.float64)


In [9]:
print(game.LH(""))

None


1