In [1]:
from Bimatrix import PayoffMatrix, Bimatrix, processArguments
import torch
import fractions

In [2]:
payoff = PayoffMatrix(None,10,5)

In [3]:
payoff.__str__()


tensor([[75.6944,  8.7106, 55.9041, 30.3979, 17.5002],
        [49.5165, 31.2749,  7.2198, 66.2829,  7.1693],
        [ 3.6857,  1.4830, 12.8070, 91.8261, 36.0214],
        [97.5284, 71.5620, 43.7392,  3.9759, 24.3781],
        [31.0885, 70.8593, 45.4988, 86.2681, 14.7214],
        [31.5800,  5.6070, 68.3446,  7.5921, 21.3308],
        [90.8613, 71.1251, 53.3883, 92.9316, 37.0985],
        [28.0054, 28.5637, 16.9229, 41.5639, 16.4013],
        [72.2697, 57.6293, 61.0833,  2.4133, 96.2516],
        [15.4162, 79.3512,  3.4074, 86.8983, 74.7353]], dtype=torch.float64)

In [4]:
payoff = PayoffMatrix(None, 2, 2)

In [5]:
torch.concat((payoff.negmatrix, torch.Tensor([[0,0]])))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [6]:
game = Bimatrix(None, 5,5)

In [7]:
print(game)

# m,n= 
5 5
# A= 
 tensor([[73.8402, 35.9579, 40.2775, 63.8543, 92.6314],
        [83.9031, 52.0634, 59.0331, 27.1275,  5.0095],
        [24.9081, 69.4155, 65.2541, 32.0303, 17.9675],
        [31.7022, 32.3345, 83.2285, 35.7701, 23.0545],
        [64.5279, 13.5209,  1.7752, 44.4636, 14.8444]], dtype=torch.float64)
# B= tensor([[11.5347, 58.0567, 21.0150, 72.5047, 54.1683],
        [20.6766, 24.2303, 57.7492, 99.7781, 46.7264],
        [77.2456, 87.1176, 70.3154, 71.8340, 32.6977],
        [11.0870, 51.6795, 39.7390, 99.1663, 54.7723],
        [76.1790, 79.0456, 73.1087,  5.8350, 89.3526]], dtype=torch.float64)


In [8]:
print(game)

# m,n= 
5 5
# A= 
 tensor([[73.8402, 35.9579, 40.2775, 63.8543, 92.6314],
        [83.9031, 52.0634, 59.0331, 27.1275,  5.0095],
        [24.9081, 69.4155, 65.2541, 32.0303, 17.9675],
        [31.7022, 32.3345, 83.2285, 35.7701, 23.0545],
        [64.5279, 13.5209,  1.7752, 44.4636, 14.8444]], dtype=torch.float64)
# B= tensor([[11.5347, 58.0567, 21.0150, 72.5047, 54.1683],
        [20.6766, 24.2303, 57.7492, 99.7781, 46.7264],
        [77.2456, 87.1176, 70.3154, 71.8340, 32.6977],
        [11.0870, 51.6795, 39.7390, 99.1663, 54.7723],
        [76.1790, 79.0456, 73.1087,  5.8350, 89.3526]], dtype=torch.float64)


In [9]:
print(game.LemkeHowson  ("1"))

After filltableau:
Determinant: -1
var  z0 z1 z2 z3 z4 z5 z6 z7 z8 z9 z10 z11 z12 RHS
scfa  1  1  1  1  1  1  1  1  1  1   1   1   1   1
                                                  
w1    .  .  .  .  .  .  .  .  .  .   .  -1   .   .
w2    1  .  .  .  .  .  .  .  .  .   .  -1   .   .
w3    1  .  .  .  .  .  .  .  .  .   .  -1   .   .
w4    1  .  .  .  .  .  .  .  .  .   .  -1   .   .
w5    1  .  .  .  .  .  .  .  .  .   .  -1   .   .
w6    1  .  .  .  .  .  .  .  .  .   .   .  -1   .
w7    1  .  .  .  .  .  .  .  .  .   .   .  -1   .
w8    1  .  .  .  .  .  .  .  .  .   .   .  -1   .
w9    1  .  .  .  .  .  .  .  .  .   .   .  -1   .
w10   1  .  .  .  .  .  .  .  .  .   .   .  -1   .
w11   1  1  1  1  1  1  .  .  .  .   .   .   .  -1
w12   1  .  .  .  .  .  1  1  1  1   1   .   .  -1
-----------------end of tableau-----------------
leaving: w12  entering: z0
leaving: w10  entering: z12
leaving: w11  entering: z10
leaving: w1   entering: z11
leaving: w5   entering: z1
Final tableau

In [10]:
fractions.Fraction("1.2")

Fraction(6, 5)